"""Updated Games model

Revision ID: 45df6aef69b2
Revises: 52953de67668
Create Date: 2025-04-29 11:57:02.035701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45df6aef69b2'
down_revision = '52953de67668'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_players', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('max_players')

    # ### end Alembic commands ###
